# Generated by Django 4.2.3 on 2023-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_videos_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='instructor',
        ),
        migrations.AddField(
            model_name='users',
            name='classroom',
            field=models.ManyToManyField(related_name='users', to='core.classroom'),
        ),
    ]
