# Generated by Django 4.2.3 on 2023-08-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.lessons')),
                ('student', models.ManyToManyField(related_name='st_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yoklama',
                'verbose_name_plural': 'Yoklamalar',
                'db_table': 'attendances',
            },
        ),
    ]
