# Generated by Django 4.2.3 on 2023-08-06 07:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_attendancemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.classroom')),
                ('instructor', models.ForeignKey(limit_choices_to={'groups__name': 'Eğitmen'}, on_delete=django.db.models.deletion.CASCADE, related_name='given_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'db_table': 'missions',
            },
        ),
    ]
