# Generated by Django 4.2.3 on 2023-08-06 12:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_missionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
