# Generated by Django 4.2.3 on 2023-08-06 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_missionmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSubmissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('url', models.URLField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.missionmodel')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Öğrenci'}, on_delete=django.db.models.deletion.CASCADE, related_name='completed_missions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görevi Tamamlayan',
                'verbose_name_plural': 'Görevi Tamamlayanlar',
                'db_table': 'mission_submissions',
            },
        ),
    ]
