# Generated by Django 4.2.3 on 2023-08-06 19:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_missionsubmissionsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='coursecategories',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='period',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='username', unique=True),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_code',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Ders Kodu'),
        ),
    ]
